from typing import Optional

WindowInfo = dict
EventDict = dict
GeometryDict = dict

def connect(display: Optional[str] = None) -> bool: ...
def disconnect() -> None: ...
def list_windows(pattern: Optional[str] = None, only_eve: bool = False) -> list[WindowInfo]: ...
def capture(wid: int, timeout_secs: int = 5) -> Optional[tuple[bytes, int, int, str]]: ...
def capture_pixmap(wid: int) -> Optional[tuple[bytes, int, int, str]]: ...
def capture_window_direct(wid: int) -> Optional[tuple[bytes, int, int, str]]: ...
def capture_sc(wid: int) -> Optional[tuple[bytes, int, int, str]]: ...
def focus_window(wid: int) -> bool: ...
def minimize_window(wid: int) -> bool: ...
def move_resize(wid: int, x: int, y: int, w: int, h: int) -> bool: ...
def set_always_on_top(wid: int | str, flag: bool) -> bool: ...
def hide_caption(wid: int) -> bool: ...
def get_geometry(wid: int) -> Optional[GeometryDict]: ...
def get_window_level(wid: int) -> Optional[int]: ...
def create_damage(wid: int) -> int: ...
def destroy_damage(damage_id: int) -> None: ...
def poll_event() -> Optional[EventDict]: ...
def register_hotkey(modifiers: int, keycode: int) -> bool: ...
def hotkey_triggered() -> bool: ...
def is_app_frontmost(pid: int) -> bool: ...
def get_window_title(wid: int) -> Optional[str]: ...
def get_active_window() -> Optional[int]: ...
def set_process_name(name: str) -> bool: ...
def is_accessibility_trusted() -> bool: ...
